version: 2
updates:
  - package-ecosystem: "npm" # npm のバージョン更新を有効にする
    # 「root」ディレクトリで「package.json」と「lock」ファイルを探す
    directory: "/"
    # npm レジストリの更新を毎日（平日）チェックする
    schedule:
      interval: "daily"
